version: 2.1

orbs:
  architect: giantswarm/architect@6.14.0

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: klaus-operator
          filters:
            tags:
              only: /^v.*/

      # Branch builds: amd64 only for faster PR feedback
      - architect/push-to-registries-multiarch:
          context: architect
          name: push-to-registries
          platforms: "linux/amd64"
          requires:
            - go-build
          filters:
            branches:
              ignore:
                - main
                - master

      # Tag builds: full multi-arch (amd64 + arm64)
      - architect/push-to-registries-multiarch:
          context: architect
          name: push-to-registries-release
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      # Branch: push chart after images
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          chart: klaus-operator
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master

      # Tag: push chart after images
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-release
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          chart: klaus-operator
          requires:
            - push-to-registries-release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
